### ISSUE TITLE
Worst-case performance of alt (perhaps need an alt_sc?)

### ISSUE THREAD

**Issue by floyd-may** [microsoft/ts-parsec#33]
The `alt` combinator has some worst-case performance behavior if there isn't a reasonably fast parse fail in any of its arguments. I discovered this during 2021's Advent of Code challenge where I used `typescript-parsec` on [this problem](https://adventofcode.com/2021/day/16). Using `alt` to determine the packet type is impossibly slow. I hand-wrote a parser to get past it, but it seems that an alt_sc may be useful to shortcut to the first succeeding argument rather than attempt parsing all arguments.

**Comment by ZihanChen-MSFT** [comment]
`alt` would give you all possible answer, but you are right, `alt_sc` might be useful when you only need one answer.
