### ISSUE TITLE
Health of the project

### ISSUE THREAD

**Issue by synlynx** [microsoft/ts-parsec#40]
Hi,

is this project still actively maintained?

I'm currently considering to use this library in one of my projects but the latest version on npm is 2 years old and I can't see any recent activities on the repo.

thx

**Comment by mstn** [comment]
Hi, I'd like to know what is the state of the project as well. I was going to build something similar for a project of mine. Thanks!

**Comment by Kreijstal** [comment]
Curious as well

**Comment by MystPi** [comment]
I have the same question as well.

**Comment by ZihanChen-MSFT** [comment]
Hi, thanks for being interested in this project!

I usually update this project when I want to add new features or fix known issues, but such project doesn't really need frequent feature updates. So it is usual that some version will last for a lone time.
